const VERTICALS = [
    "AgTech",
    "Artificial Intelligence & Machine Learning",
    "CleanTech",
    "Climate Tech",
    "E-Commerce",
    "EdTech",
    "FinTech",
    "HealthTech",
    "SaaS",
    "Cryptocurrency Blockchain",
    "Digital Health",
    "AdTech",
    "Big Data",
    "Cannabis",
    "Cybersecurity",
    "FemTech",
    "Gaming",
    "HR Tech",
    "Impact Investing",
    "InsurTech",
    "Internet of Things",
    "Legal Tech",
    "Life Sciences",
    "Marketing Tech",
    "Virtual Reality",
    "3D Printing",
    "Advanced Manufacturing",
    "AudioTech",
    "Augmented Reality",
    "Autonomous cars",
    "B2B Payments",
    "Beauty",
    "Car-Sharing",
    "CloudTech & DevOps",
    "Construction Technology",
    "Ephemeral Content",
    "Esports",
    "FoodTech",
    "Industrials",
    "Infrastructure",
    "LOHAS & Wellness",
    "Manufacturing",
    "Micro-Mobility",
    "Mobile",
    "Mobile Commerce",
    "Mobility Tech",
    "Mortgage Tech",
    "Nanotechnology",
    "Oil & Gas",
    "Oncology",
    "Pet Technology",
    "Real Estate Technology",
    "Restaurant Technology",
    "Ridesharing",
    "Robotics and Drones",
    "Space Technology",
    "Supply Chain Tech",
    "TMT",
    "Wearables & Quantified Self"
];

const INDUSTRIES = [
    "Business Products and Services (B2B)",
    "Consumer Products and Services (B2C)",
    "Energy",
    "Financial Services",
    "Healthcare",
    "Information Technology",
    "Materials and Resources",
    "Aerospace and Defense",
    "Automotive",
    "Commercial Products",
    "Commercial Services",
    "Commercial Transportation",
    "Apparel and Accessories",
    "Consumer Durables",
    "Consumer Non-Durables",
    "Media",
    "Restaurants, Hotels and Leisure",
    "Retail",
    "Services (Non-Financial)",
    "Transportation",
    "Energy Equipment",
    "Exploration, Production and Refining",
    "Energy Services",
    "Utilities",
    "Capital Markets/Institutions",
    "Insurance",
    "Healthcare Devices and Supplies",
    "Clinics/Outpatient Services",
    "Healthcare Technology Systems",
    "Pharmaceuticals and Biotechnology",
    "Communications and Networking",
    "Computers, Parts and Peripherals",
    "Semiconductors",
    "IT Services",
    "Software",
    "Agriculture",
    "Chemicals and Gases",
    "Construction (Non-Wood)",
    "Containers and Packaging",
    "Forestry",
    "Metals, Minerals and Mining",
    "Textiles"
];

module.exports = { VERTICALS, INDUSTRIES };